In [1]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import MaxPooling2D
from keras.layers import Convolution2D
from keras.layers import Dropout

Using TensorFlow backend.
C:\Users\HOME\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\HOME\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\HOME\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\HOME\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519

In [2]:
model=Sequential()

In [3]:
model.add(Convolution2D(64,(3,3),input_shape=(128,128,3),activation='relu'))

In [4]:
model.add(MaxPooling2D(pool_size=(2,2)))

In [5]:
model.add(Dropout(0.5))

In [6]:
model.add(Flatten())

In [7]:
model.add(Dense(output_dim=128,activation='relu',init='uniform'))

C:\Users\HOME\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=128, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [8]:
model.add(Dense(output_dim=128,activation='relu',init='uniform'))

C:\Users\HOME\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=128, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [9]:
model.add(Dense(output_dim=128,activation='relu',init='uniform'))

C:\Users\HOME\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=128, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [10]:
model.add(Dense(output_dim=5,activation='softmax',init='uniform'))

C:\Users\HOME\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", units=5, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [11]:
from keras.preprocessing.image import ImageDataGenerator
train_data=ImageDataGenerator(rescale=1./255,shear_range=0.2,zoom_range=0.2,horizontal_flip=True)
test_data=ImageDataGenerator(rescale=1./255)

In [12]:
xtrain=train_data.flow_from_directory('E:/Vehicles/trainset',target_size=(128,128),batch_size=32,class_mode='categorical')

Found 1885 images belonging to 5 classes.


In [13]:
print(xtrain.class_indices)

{'aeroplane': 0, 'bicycle': 1, 'car': 2, 'cargoship': 3, 'truck': 4}


In [14]:
xtest=test_data.flow_from_directory('E:/Vehicles/testset',target_size=(128,128),batch_size=32,class_mode='categorical')

Found 564 images belonging to 5 classes.


In [15]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [27]:
model.fit_generator(xtrain,steps_per_epoch=60,epochs=25,validation_data=xtest,validation_steps=40)

Epoch 1/25
60/60 [==============================] - 69s 1s/step - loss: 0.3376 - accuracy: 0.8586 - val_loss: 0.6755 - val_accuracy: 0.7930
Epoch 2/25
60/60 [==============================] - 70s 1s/step - loss: 0.3205 - accuracy: 0.8612 - val_loss: 0.4156 - val_accuracy: 0.7842
Epoch 3/25
60/60 [==============================] - 70s 1s/step - loss: 0.3062 - accuracy: 0.8722 - val_loss: 1.1557 - val_accuracy: 0.7723
Epoch 4/25
60/60 [==============================] - 69s 1s/step - loss: 0.2987 - accuracy: 0.8795 - val_loss: 0.8909 - val_accuracy: 0.7826
Epoch 5/25
60/60 [==============================] - 70s 1s/step - loss: 0.3064 - accuracy: 0.8764 - val_loss: 0.4409 - val_accuracy: 0.7379
Epoch 6/25
60/60 [==============================] - 69s 1s/step - loss: 0.2514 - accuracy: 0.9004 - val_loss: 0.6924 - val_accuracy: 0.7779
Epoch 7/25
60/60 [==============================] - 70s 1s/step - loss: 0.2180 - accuracy: 0.9181 - val_loss: 0.7986 - val_accuracy: 0.7540
Epoch 8/25
60/60 [==

In [28]:
model.save("vehicles.h5")

In [29]:
from keras.preprocessing import image
import numpy as np
import cv2
from keras.models import load_model

In [50]:
img=image.load_img('D:/cargoship1.png',target_size=(128,128))
x=image.img_to_array(img)
x=np.expand_dims(x,axis=0)

In [51]:
x.shape

(1, 128, 128, 3)

In [52]:
pred=model.predict_classes(x)

In [53]:
pred

array([3], dtype=int64)

In [60]:
img=image.load_img('D:/aeroplane1.png',target_size=(128,128))
x=image.img_to_array(img)
x=np.expand_dims(x,axis=0)
pred=model.predict_classes(x)
pred

array([0], dtype=int64)

In [66]:
img=image.load_img('D:/bicycle2.png',target_size=(128,128))
x=image.img_to_array(img)
x=np.expand_dims(x,axis=0)
pred=model.predict_classes(x)
pred

array([1], dtype=int64)

In [67]:
img=image.load_img('D:/truck1.png',target_size=(128,128))
x=image.img_to_array(img)
x=np.expand_dims(x,axis=0)
pred=model.predict_classes(x)
pred

array([4], dtype=int64)

In [65]:
img=image.load_img('D:/car1.png',target_size=(128,128))
x=image.img_to_array(img)
x=np.expand_dims(x,axis=0)
pred=model.predict_classes(x)
pred

array([2], dtype=int64)