In [1]:

import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("E:/pythonbasics/50_Startups.csv")

In [3]:
data.head(5)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
data.isnull().any()

R&D Spend          False
Administration     False
Marketing Spend    False
State              False
Profit             False
dtype: bool

In [5]:
from sklearn.preprocessing import LabelEncoder
atm=LabelEncoder()
data['State']=atm.fit_transform(data['State'])

In [6]:
data[0:3]

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39

In [7]:
x=data.iloc[:,:4].values
y=data.iloc[:,4:].values#toconvert to arrays

In [8]:
x[0:3,0:]

array([[1.6534920e+05, 1.3689780e+05, 4.7178410e+05, 2.0000000e+00],
       [1.6259770e+05, 1.5137759e+05, 4.4389853e+05, 0.0000000e+00],
       [1.5344151e+05, 1.0114555e+05, 4.0793454e+05, 1.0000000e+00]])

In [9]:
from sklearn.preprocessing import OneHotEncoder
one=OneHotEncoder()
z=one.fit_transform(x[:,3:4]).toarray()
x=np.delete(x,3,axis=1)
x=np.concatenate((z,x),axis=1)

In [10]:
x[0:4,0:]

array([[0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.6534920e+05,
        1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.6259770e+05,
        1.5137759e+05, 4.4389853e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.5344151e+05,
        1.0114555e+05, 4.0793454e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.4437241e+05,
        1.1867185e+05, 3.8319962e+05]])

In [11]:
x[0:2,0:]

array([[0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.6534920e+05,
        1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.6259770e+05,
        1.5137759e+05, 4.4389853e+05]])

In [12]:
x.ndim

2

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [14]:
x_train.shape

(40, 6)

In [15]:
x_train[0:3,0:]

array([[0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 5.5493950e+04,
        1.0305749e+05, 2.1463481e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 4.6014020e+04,
        8.5047440e+04, 2.0551764e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 7.5328870e+04,
        1.4413598e+05, 1.3405007e+05]])

In [16]:
x_test.shape

(10, 6)

In [17]:
y_train.shape

(40, 1)

In [18]:
y_test.shape

(10, 1)

In [19]:
from sklearn.preprocessing import StandardScaler #donot use  standard scaling when there is no variation among the variables
sc = StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [20]:
x_train[0:2,0:]

array([[-0.81649658,  1.73205081, -0.73379939, -0.35006454, -0.78547109,
         0.1011968 ],
       [-0.81649658, -0.57735027,  1.36277029, -0.55530319, -1.48117426,
         0.02734979]])

In [21]:
x_test[0:2,0:]

array([[-0.81649658,  1.73205081, -0.73379939, -0.1214952 ,  2.2889053 ,
        -0.68032287],
       [ 1.22474487, -0.57735027, -0.73379939,  0.6280306 , -1.22069499,
         0.38557774]])

In [22]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.
C:\Users\HOME\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\HOME\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\HOME\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\HOME\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519

In [23]:
regressor=Sequential()

In [24]:
x_train.shape

(40, 6)

In [52]:
regressor.add(Dense(units=6,init='random_uniform',activation='relu'))

C:\Users\HOME\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=6, activation="relu", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [53]:
regressor.add(Dense(output_dim=3,init='random_uniform',activation='relu'))

C:\Users\HOME\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=3, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [55]:
regressor.add(Dense(output_dim=1,init='random_uniform',activation='relu')) #noneed to add activation for regression

C:\Users\HOME\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=1, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [56]:
regressor.compile(optimizer = 'adam', loss = 'mse', metrics = ['mse'])

In [57]:
regressor.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
40/40 [==============================] - 0s 7ms/step - loss: 13615996108.8000 - mean_squared_error: 13615996108.8000
Epoch 2/100
40/40 [==============================] - 0s 100us/step - loss: 13615996108.8000 - mean_squared_error: 13615996108.8000
Epoch 3/100
40/40 [==============================] - 0s 99us/step - loss: 13615994470.4000 - mean_squared_error: 13615994470.4000
Epoch 4/100
40/40 [==============================] - 0s 100us/step - loss: 13615994265.6000 - mean_squared_error: 13615994265.6000
Epoch 5/100
40/40 [==============================] - 0s 100us/step - loss: 13615992832.0000 - mean_squared_error: 13615992832.0000
Epoch 6/100
40/40 [==============================] - 0s 99us/step - loss: 13615993446.4000 - mean_squared_error: 13615993446.4000
Epoch 7/100
40/40 [==============================] - 0s 100us/step - loss: 13615992422.4000 - mean_squared_error: 13615992422.4000
Epoch 8/100
40/40 [==============================] - 0s 100us/step - loss: 13615992422.

In [58]:
ypred = regressor.predict(x_test)#prediction

In [30]:
ypred[0:3]

array([[1.2285085e-05],
       [0.0000000e+00],
       [2.8829023e-05]], dtype=float32)

In [31]:
 y_test #keypaper 

array([[103282.38],
       [144259.4 ],
       [146121.95],
       [ 77798.83],
       [191050.39],
       [105008.31],
       [ 81229.06],
       [ 97483.56],
       [110352.25],
       [166187.94]])

In [32]:
n   

In [33]:
accuracy

-11.69118972850078

In [34]:
ypred= (ypred>0.5)

In [35]:
ypred[5]

array([False])

In [36]:
ypred[2]

array([False])

In [37]:
y_test[2]

array([146121.95])

In [38]:
print(ypred[7])
print(y_test[7])

[False]
[97483.56]


In [40]:
yp=regressor.predict(sc.transform(np.array([[0,0,1,10000,1000,1000]]))) #5 columns

In [41]:
yp

array([[-6.726932e-05]], dtype=float32)

In [42]:
yp=yp>0.5

In [43]:
yp

array([[False]])

In [46]:
yp1 = regressor.predict(sc.transform(np.array([[0,1,0,987500,10700,15000]])))


In [47]:
yp1

array([[3.6045698e-05]], dtype=float32)

In [48]:
yp2=yp1>0.5

In [49]:
yp2

array([[False]])

In [51]:
regressor.save("ann-startups.h5")