In [7]:
from keras.models import load_model
from keras.preprocessing import image


import numpy as np
import cv2

In [8]:
model=load_model("cnn.h5")

In [9]:
img=image.load_img(r'C:\Users\HOME\Desktop\cat2.png',target_size=(64,64))
x=image.img_to_array(img) #converting image to arrays
x=np.expand_dims(x,axis=0)  #expanding dimensions bcoz CNN needs 4 dims

C:\Users\HOME\anaconda3\lib\site-packages\PIL\Image.py:932: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  "Palette images with Transparency expressed in bytes should be "


In [11]:
x.shape

(1, 64, 64, 3)

In [13]:
pred=model.predict_classes(x)  

In [14]:
pred

array([[1]])

In [16]:
pred[0]

array([1])

In [21]:
pred.shape

(1, 1)

In [22]:
pre=model.predict(x)

In [23]:
pre

array([[1.]], dtype=float32)

In [25]:
pre[0]

array([1.], dtype=float32)