In [1]:
import numpy as np

In [2]:
lista=[1,2,3,4,5]
type(lista)

list

In [8]:
a=np.array(lista)
type(a)
a

array([1, 2, 3, 4, 5])

In [6]:
a.ndim

1

In [15]:
list1=[1,2,"james",3,"string",4]
import numpy as np
a=np.array(list1)

In [16]:
a

array(['1', '2', 'james', '3', 'string', '4'], dtype='<U11')

In [19]:
a[2]


'james'

In [20]:
a[:4]

array(['1', '2', 'james', '3'], dtype='<U11')

In [21]:
a[2:]

array(['james', '3', 'string', '4'], dtype='<U11')

In [22]:
a[1:3]

array(['2', 'james'], dtype='<U11')

In [23]:
listn=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]
type(listn)

list

In [24]:
a=np.array(listn)

In [64]:
a

array([[ 1,  2, 27,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
a[[0,1,2],[0,1,2]]

array([ 1,  6, 11])

In [46]:
a[2,2]

11

In [49]:
a[0,2]=27

In [50]:
a

array([[ 1,  2, 27,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
a[[2,1,2],[1,2,3]]

array([10,  7, 12])

In [44]:
a[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [43]:
a[1:2,1:2]

array([[6]])

In [26]:
a.ndim

2

In [27]:
a.shape  #for rows and columns

(3, 4)

In [30]:
a[0]

array([1, 2, 3, 4])

In [33]:
a[1:3] 

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
a[0:4,2:3] #column matrix

array([[ 3],
       [ 7],
       [11]])

In [41]:
a[:,1:2]  #for grabbing column matrix

array([[ 2],
       [ 6],
       [10]])

In [68]:
import numpy as np

In [75]:
ary1=[[2,4,6],[1,3,5],[8,10,12]]
k = np.array(ary1)

In [76]:
k

array([[ 2,  4,  6],
       [ 1,  3,  5],
       [ 8, 10, 12]])

In [77]:
ar1=[[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]]
ark=np.array(ar1)
ark

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [87]:
ark[[0,1,3,3],[0,0,0,3]]

array([ 0,  4, 12, 15])

In [90]:
a=np.arange(10)

In [91]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
a=np.arange(10,40)

In [93]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [94]:
a=np.arange(10,40,3)

In [95]:
a

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37])

In [99]:
ar=np.zeros((2))

In [100]:
ar

array([0., 0.])

In [101]:
art=np.zeros((3,3))

In [102]:
art

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [104]:
a=np.ones((4,4))

In [105]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [106]:
a=np.eye(3)

In [107]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [109]:
a=np.linspace(4,6)

In [110]:
a

array([4.        , 4.04081633, 4.08163265, 4.12244898, 4.16326531,
       4.20408163, 4.24489796, 4.28571429, 4.32653061, 4.36734694,
       4.40816327, 4.44897959, 4.48979592, 4.53061224, 4.57142857,
       4.6122449 , 4.65306122, 4.69387755, 4.73469388, 4.7755102 ,
       4.81632653, 4.85714286, 4.89795918, 4.93877551, 4.97959184,
       5.02040816, 5.06122449, 5.10204082, 5.14285714, 5.18367347,
       5.2244898 , 5.26530612, 5.30612245, 5.34693878, 5.3877551 ,
       5.42857143, 5.46938776, 5.51020408, 5.55102041, 5.59183673,
       5.63265306, 5.67346939, 5.71428571, 5.75510204, 5.79591837,
       5.83673469, 5.87755102, 5.91836735, 5.95918367, 6.        ])

In [114]:
a=np.linspace(10,40,20)

In [115]:
a

array([10.        , 11.57894737, 13.15789474, 14.73684211, 16.31578947,
       17.89473684, 19.47368421, 21.05263158, 22.63157895, 24.21052632,
       25.78947368, 27.36842105, 28.94736842, 30.52631579, 32.10526316,
       33.68421053, 35.26315789, 36.84210526, 38.42105263, 40.        ])

In [116]:
a.min()

10.0

In [117]:
a.argmin()

0

In [118]:
a.max()

40.0

In [119]:
a.argmax()

19

In [122]:
c=np.random.rand(1,3)

In [123]:
c

array([[0.84506016, 0.05891375, 0.67583413]])

In [125]:
c=np.random.rand(2,4) #creates 2 rows 4 columns with random nos

In [126]:
c

array([[0.45757603, 0.26007794, 0.15995499, 0.8449177 ],
       [0.64013775, 0.00679121, 0.57044396, 0.28553856]])

In [129]:
d=np.random.randint(1000)

In [130]:
d

851

In [144]:
 e=np.random.randint(3) #creates 1 random integer number within range 3

In [145]:
e

2

In [148]:
f=np.random.rand(2) #creates 2 random floating numbers

In [149]:
f

array([0.7190217 , 0.19059543])

In [151]:
g=np.random.randint(1,40,20)


In [152]:
g

array([ 9, 29, 27, 29, 15,  3, 25, 14, 23, 35,  1,  9, 18, 29, 29, 20, 29,
       18, 37, 33])

In [158]:
f=np.arange(9)

In [159]:
f

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [160]:
k=f.reshape(3,3)

In [161]:
k

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [178]:
k=np.arange(12)

In [179]:
k

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [181]:
m=k.ravel()

In [182]:
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [183]:
j=k.ravel()

In [184]:
j[7]=49

In [185]:
j

array([ 0,  1,  2,  3,  4,  5,  6, 49,  8,  9, 10, 11])

In [166]:
k

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6, 49,  8]])

In [189]:
a=np.arange(9)

In [190]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [201]:
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [204]:
a.reshape(3,3)
m=np.transpose(a)
m

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [200]:
m

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [209]:
lista = [[1,2,3],[4,5,6],[7,8,9]]

In [210]:
lk=np.array(lista)

In [211]:
lk

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [212]:
m=lk.transpose()

In [213]:
m

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [216]:
n=np.concatenate((lk,m))

In [217]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [219]:
ar1=m+m

In [220]:
m

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [221]:
ar1

array([[ 2,  8, 14],
       [ 4, 10, 16],
       [ 6, 12, 18]])

In [222]:
ar1=m-m

In [223]:
ar1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [224]:
np.sqrt(m)

array([[1.        , 2.        , 2.64575131],
       [1.41421356, 2.23606798, 2.82842712],
       [1.73205081, 2.44948974, 3.        ]])

In [225]:
np.exp(m)

array([[2.71828183e+00, 5.45981500e+01, 1.09663316e+03],
       [7.38905610e+00, 1.48413159e+02, 2.98095799e+03],
       [2.00855369e+01, 4.03428793e+02, 8.10308393e+03]])

In [226]:
np.sin(m)

array([[ 0.84147098, -0.7568025 ,  0.6569866 ],
       [ 0.90929743, -0.95892427,  0.98935825],
       [ 0.14112001, -0.2794155 ,  0.41211849]])

In [227]:
m[m%2==0]

array([4, 2, 8, 6])